main: nl.dusdavidgames.kingdomfactions.KingdomFactionsPlugin
name: KingdomFactions
version: 1.0.0
authors: [steenooo, wouter_MC, Jannyboy11]
commands:
  endersee:
    description: Enter a player's enderchest!
    aliases: [enderchest]
  invsee:
    description: Enter a player's inventory!
    aliases: [inventory]
  fly:
    description: Enable or disable fly mode!
  nightvision:
    description: Toggle nightvision!
  tp:
    description: Teleport to a player!
  tphere:
    description: Teleport a player to your location!
  godmode:
    description: Switch godmode on or off!
    aliases: [god]
  time:
    description: Display your time
  gamemode:
    description: Switch between gamemodes!
    aliases: [gm]
  channel:
    description: Channel command
    aliases: [c]
  reply:
    description: Respond to a private message
    aliases: [r]
  msg:
    description: Send a private message
    aliases: [tell, whisper]
  kingdom:
    description: Main command for kingdoms
    aliases: [kd, k]
  faction:
    description: Main command for factions
    aliases: [f, fac]
  say:
    description: Say something in the chat
  broadcast:
    description: Broadcast a message
    aliases: [bc]
  pay:
    description: Pay command
  coins:
    description: Coins command
  nexus:
    description: Nexus command
  spy:
    description: Enable or disable spy mode!
  influence:
    description: Influence main command
  speed:
    description: Set or get speed!
  war:
    description: War command
  reloadconfig:
    description: Reload the config
  help:
    description: Help command
  admin:
    description: Admin command
    aliases: [a]
  kit:
    description: Test kit command
  deathban:
    description: Deathban command
  list:
    description: List players or factions
  lag:
    description: Displays lag-related information
    aliases: [lagg]
  empirewand:
    description: Create an EmpireWand
    aliases: [ew]
  informatie:
    description: Get information about a player
  wreckingball:
    description: Get a wreckingball
  shop:
    description: Main shop command
  setmine:
    description: Set the spawn mining location!
  logout:
    description: Log out if you're in combat
  combat:
    description: Main combat command
  setting:
    description: Settings command
  spawn:
    description: Spawn command!
  data:
    description: Get all amounts of data lists

permissions:
  kingdomfactions.role.lead:
    description: Gives access to all permissions needed for Leadership
    default: op
    children:
      kingdomfactions.role.pl: true

  kingdomfactions.role.pl:
    description: Gives access to all permissions needed for rank PL
    default: false
    children:
      kingdomfactions.role.mod: true
      kingdomfactions.command.gamemode: true
      kingdomfactions.command.broadcast: true
      kingdomfactions.command.speed: true
      kingdomfactions.command.influence.remove: true
      kingdomfactions.command.influence.add: true
      kingdomfactions.command.coins.add: true
      kingdomfactions.command.coins.remove: true
      kingdomfactions.command.empirewand: true
      kingdomfactions.command.commandcheck: true

  kingdomfactions.role.mod:
    description: Gives access to all permissions needed for rank mod
    default: false
    children:
      kingdomfactions.role.support: true
      kingdomfactions.command.deathban: true
      kingdomfactions.command.endersee: true
      kingdomfactions.command.fly: true
      kingdomfactions.command.godmode: true
      kingdomfactions.command.invsee: true
      kingdomfactions.command.nightvision: true
      kingdomfactions.command.teleport: true
      kingdomfactions.command.tphere: true
      kingdomfactions.command.lag: true
      kingdomfactions.command.influence.ignore: true
      kingdomfactions.command.kingdom.spawn: true

  kingdomfactions.role.support:
    description: Gives access to all permissions needed for rank support
    default: false
    children:
      kingdomfactions.command.deathban: true
      kingdomfactions.command.endersee: true
      kingdomfactions.command.fly: true
      kingdomfactions.command.godmode: true
      kingdomfactions.command.invsee: true
      kingdomfactions.command.nightvision: true
      kingdomfactions.command.teleport: true
      kingdomfactions.command.tphere: true
      kingdomfactions.command.lag: true
      kingdomfactions.role.speler: true
      kingdomfactions.command.kingdom: true
      kingdomfactions.command.kingdom.check: true
      kingdomfactions.deathban.ignore: true
      kingdomfactions.command.wreckingball: true
      coreprotect.inspect: true

  kingdomfactions.role.speler:
    description: Gives access to all permissions needed for rank speler
    default: true
    children:
      kingdomfactions.command.nexus.create: true
      kingdomfactions.command.nexus.build: true
      kingdomfactions.command.influence.check: true
      kingdomfactions.command.switch: true
      kingdomfactions.command.oorlog.info: true
      kingdomfactions.command.time: true
      kingdomfactions.command.influence.check: true
      kingdomfactions.command.faction: true
      kingdomfactions.command.influence: true
      kingdomfactions.command.channel: true
      kingdomfactions.command.nexus: true
      kingdomfactions.command.channel.join: true
      kingdomfactions.command.channel.leave: true
      kingdomfactions.command.channel.switchto: true
      kingdomfactions.command.pay: true
      kingdomfactions.command.msg: true
      kingdomfactions.command.reply: true
      kingdomfactions.command.combat.check: true
      kingdomfactions.command.help: true
      kingdomfactions.command.logout: true
